### ISSUE TITLE
Where to get polimorfologik.txt?

### ISSUE THREAD

**Issue by dweiss** [morfologik/morfologik-scripts#3]

**Comment by dweiss** [comment]
After a move from SourceForge the prebuilt packages of morfologik source data are no longer available. 

To get the source of the Polish dictionary (former polimorfologik.txt) you can:

- Go to:
https://github.com/morfologik/morfologik-stemming/releases
- Fetch a release of morfologik-tools-*.zip, for example:
https://github.com/morfologik/morfologik-stemming/releases/download/2.0.1/morfologik-tools-2.0.1-package.zip
- Checkout the latest dictionary:
```
git clone --depth 1 git@github.com:morfologik/morfologik-stemming.git
```
- Decompile the Polish dictionary back to .txt form:
```
java -jar lib/morfologik-tools-2.0.1.jar dict_decompile -i morfologik-stemming/morfologik-polish/src/main/resources/morfologik/stemming/polish/pl.dict
```
- The output is UTF-8 encoded and ';' separated at:
```
morfologik-stemming/morfologik-polish/src/main/resources/morfologik/stemming/polish/pl.input
```

I will also attach the latest binaries of the "synth" dictionary to this project, but these won't work

**Comment by dweiss** [comment]
I also added polimorfologik.txt (the source of the dictionary) to this repo.

**Comment by dweiss** [comment]
Couldn't do it, there is a file limit of 100mb and large files extension didn't work for me. Adding a binary release

**Comment by dweiss** [comment]
https://github.com/morfologik/polimorfologik/releases/download/archival%2Fsourceforge%2F2.0.0/morfologik.zip

**Comment by tomsien** [comment]
Where can I find new dict_synth ? I tried to rebuild it but after executing command
java -jar morfologik-tools-2.0.1\lib\morfologik-tools-2.0.1.jar  tab2morph -nw -i synt.txt -o synt_in.txt

I got Invalid argument: com.beust.jcommander.MissingCommandException: Expected a comma
nd, got tab2morph
I have only fsa_build, fsa_dump,  fsa_info, dict_compile, dict_decompile commands available.

**Comment by dweiss** [comment]
Apologies for kicking in late. The synthesis dictionary (for Polish) is available as part of polimorfologik's distribution now.
